import type { DietaryTag, MenuItemBadge } from "../../src/lib/menu/menu-types";

/**
 * Reference menu data for the seed (single source of truth for what a fresh
 * database contains). Slugs are derived at seed time — categories use their
 * `id`, items use a slugified `name`.
 */

export interface SeedMenuCategory {
  id: string;
  name: string;
  nameAm: string;
  sortOrder: number;
  isActive: boolean;
}

export interface SeedMenuItem {
  id: string;
  categoryId: string;
  name: string;
  nameAm: string;
  description: string;
  price: number;
  image?: string;
  isAvailable: boolean;
  isFeatured: boolean;
  dietaryTags: DietaryTag[];
  badges: MenuItemBadge[];
  sortOrder: number;
}

export const MENU_CATEGORIES: SeedMenuCategory[] = [
  { id: "breakfast", name: "Breakfast", nameAm: "እራት ማግስት", sortOrder: 1, isActive: true },
  { id: "starters", name: "Starters", nameAm: "መክሰስ", sortOrder: 2, isActive: true },
  { id: "ethiopian", name: "Ethiopian Favorites", nameAm: "ባህላዊ ምግቦች", sortOrder: 3, isActive: true },
  { id: "main", name: "Main Course", nameAm: "ዋና ምግብ", sortOrder: 4, isActive: true },
  { id: "grill", name: "Grill", nameAm: "የተጠበሰ", sortOrder: 5, isActive: true },
  { id: "vegetarian", name: "Vegetarian", nameAm: "ጾም ምግብ", sortOrder: 6, isActive: true },
  { id: "sides", name: "Sides", nameAm: "ጎን ምግቦች", sortOrder: 7, isActive: true },
  { id: "desserts", name: "Desserts", nameAm: "ጣፋጭ ምግቦች", sortOrder: 8, isActive: true },
  { id: "drinks", name: "Drinks", nameAm: "መጠጥ", sortOrder: 9, isActive: true },
];

export const MENU_ITEMS: SeedMenuItem[] = [
  // ── Breakfast ──────────────────────────────────────────────
  {
    id: "breakfast-1",
    categoryId: "breakfast",
    name: "Chechebsa",
    nameAm: "ቸቸብሳ",
    description: "Torn pieces of flatbread sautéed in spiced butter and served with honey.",
    price: 320,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-dairy"],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "breakfast-2",
    categoryId: "breakfast",
    name: "Firfir",
    nameAm: "ፍርፍር",
    description: "Shredded injera tossed in a rich berbere-spiced tomato sauce.",
    price: 280,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy", "contains-dairy"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "breakfast-3",
    categoryId: "breakfast",
    name: "Genfo",
    nameAm: "ገንፎ",
    description: "Thick barley porridge with a well of spiced butter in the center.",
    price: 240,
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-dairy"],
    badges: [],
    sortOrder: 3,
  },
  {
    id: "breakfast-4",
    categoryId: "breakfast",
    name: "Ful Medames",
    nameAm: "ፉል",
    description: "Slow-cooked fava beans seasoned with cumin, chili, and fresh herbs.",
    price: 260,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 4,
  },
  {
    id: "breakfast-5",
    categoryId: "breakfast",
    name: "Breakfast Platter",
    nameAm: "የእራት ማግስት ፕሌተር",
    description: "Scrambled eggs, ayib cheese, toast, and a side of fresh vegetables.",
    price: 480,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: true,
    dietaryTags: ["contains-dairy"],
    badges: ["popular"],
    sortOrder: 5,
  },

  // ── Starters ──────────────────────────────────────────────
  {
    id: "starters-1",
    categoryId: "starters",
    name: "Sambusa",
    nameAm: "ሳምቡሳ",
    description: "Crispy pastry triangles filled with spiced beef and onions.",
    price: 220,
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy"],
    badges: ["popular"],
    sortOrder: 1,
  },
  {
    id: "starters-2",
    categoryId: "starters",
    name: "Azifa",
    nameAm: "አዚፋ",
    description: "Cold green lentil salad with mustard, jalapeño, and fresh lime.",
    price: 240,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "starters-3",
    categoryId: "starters",
    name: "Timatim Fitfit",
    nameAm: "ቶማቲም ፍትፊት",
    description: "Injera pieces mixed with a refreshing tomato, onion, and chili salad.",
    price: 250,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan"],
    badges: [],
    sortOrder: 3,
  },
  {
    id: "starters-4",
    categoryId: "starters",
    name: "Ayib & Honeycomb",
    nameAm: "አይብ እና ዛፍ ማር",
    description: "Fresh cottage cheese served alongside golden honeycomb.",
    price: 340,
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-dairy", "vegetarian"],
    badges: [],
    sortOrder: 4,
  },
  {
    id: "starters-5",
    categoryId: "starters",
    name: "Buticha",
    nameAm: "ቡቲቻ",
    description: "Creamy chickpea purée with lemon, cumin, and a hint of garlic.",
    price: 260,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan"],
    badges: [],
    sortOrder: 5,
  },

  // ── Ethiopian Favorites ───────────────────────────────────
  {
    id: "ethiopian-1",
    categoryId: "ethiopian",
    name: "Doro Wot",
    nameAm: "ዶሮ ወጥ",
    description: "Slow-braised chicken in a rich berbere sauce, served with a hard-boiled egg.",
    price: 780,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: true,
    dietaryTags: ["spicy"],
    badges: ["chef-pick"],
    sortOrder: 1,
  },
  {
    id: "ethiopian-2",
    categoryId: "ethiopian",
    name: "Kitfo",
    nameAm: "ክትፎ",
    description: "Finely minced beef blended with spiced butter and mitmita chili.",
    price: 720,
    isAvailable: true,
    isFeatured: true,
    dietaryTags: ["spicy", "contains-dairy"],
    badges: ["chef-pick"],
    sortOrder: 2,
  },
  {
    id: "ethiopian-3",
    categoryId: "ethiopian",
    name: "Special Tibs",
    nameAm: "ስፔሻል ጥብስ",
    description: "Premium cubed beef sautéed with rosemary, peppers, and jalapeños.",
    price: 850,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: true,
    dietaryTags: [],
    badges: ["chef-pick", "popular"],
    sortOrder: 3,
  },
  {
    id: "ethiopian-4",
    categoryId: "ethiopian",
    name: "Shiro Wot",
    nameAm: "ሽሮ ወጥ",
    description: "Thick chickpea flour stew simmered with onions and berbere.",
    price: 520,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan"],
    badges: ["popular"],
    sortOrder: 4,
  },
  {
    id: "ethiopian-5",
    categoryId: "ethiopian",
    name: "Misir Wot",
    nameAm: "ምስር ወጥ",
    description: "Red lentils slow-cooked in a vibrant berbere and onion sauce.",
    price: 480,
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "spicy"],
    badges: [],
    sortOrder: 5,
  },
  {
    id: "ethiopian-6",
    categoryId: "ethiopian",
    name: "Dulet",
    nameAm: "ዱሌት",
    description: "A bold mix of minced beef, liver, and tripe sautéed with mitmita.",
    price: 700,
    image: "https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy"],
    badges: [],
    sortOrder: 6,
  },
  {
    id: "ethiopian-7",
    categoryId: "ethiopian",
    name: "Alicha Wot",
    nameAm: "አሊቻ ወጥ",
    description: "Mild turmeric-based stew with tender chicken and potatoes.",
    price: 650,
    image: "https://images.unsplash.com/photo-1543353071-873f17a7a088?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: [],
    sortOrder: 7,
  },

  // ── Main Course ───────────────────────────────────────────
  {
    id: "main-1",
    categoryId: "main",
    name: "Derek Tibs",
    nameAm: "ደረቅ ጥብስ",
    description: "Dry-fried beef cubes seasoned with rosemary and jalapeño.",
    price: 820,
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy"],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "main-2",
    categoryId: "main",
    name: "Lamb Tibs",
    nameAm: "የበግ ጥብስ",
    description: "Tender lamb shoulder sautéed with onions, peppers, and rosemary.",
    price: 900,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "main-3",
    categoryId: "main",
    name: "Beyaynetu Platter",
    nameAm: "በያይነቱ",
    description: "A generous sampler of seven vegetarian stews served on injera.",
    price: 580,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: true,
    dietaryTags: ["vegan", "gluten-free"],
    badges: ["popular"],
    sortOrder: 3,
  },
  {
    id: "main-4",
    categoryId: "main",
    name: "Zilzil Tibs",
    nameAm: "ዝልዝል ጥብስ",
    description: "Long strips of prime beef flash-fried with garlic and green pepper.",
    price: 850,
    image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: [],
    sortOrder: 4,
  },
  {
    id: "main-5",
    categoryId: "main",
    name: "Kuanta Firfir",
    nameAm: "ቋንጣ ፍርፍር",
    description: "Slow-braised beef strips shredded and tossed in spiced butter.",
    price: 750,
    image: "https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy"],
    badges: [],
    sortOrder: 5,
  },

  // ── Grill ─────────────────────────────────────────────────
  {
    id: "grill-1",
    categoryId: "grill",
    name: "Shish Kebab",
    nameAm: "ሽሽ ክባብ",
    description: "Marinated lamb and beef skewers grilled over charcoal.",
    price: 950,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "grill-2",
    categoryId: "grill",
    name: "Mixed Grill Platter",
    nameAm: "ማይክድ ግሪል ፕሌተር",
    description: "A feast of charcoal-grilled lamb, chicken, and beef with sides.",
    price: 1350,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: true,
    dietaryTags: [],
    badges: ["chef-pick"],
    sortOrder: 2,
  },
  {
    id: "grill-3",
    categoryId: "grill",
    name: "Grilled Chicken",
    nameAm: "የተጠበሰ ዶሮ",
    description: "Whole free-range chicken marinated in Ethiopian spices and charcoal-grilled.",
    price: 780,
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["spicy"],
    badges: [],
    sortOrder: 3,
  },

  // ── Vegetarian ────────────────────────────────────────────
  {
    id: "vegetarian-1",
    categoryId: "vegetarian",
    name: "Gomen",
    nameAm: "ጎመን",
    description: "Collard greens sautéed with garlic, ginger, and a touch of oil.",
    price: 340,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "vegetarian-2",
    categoryId: "vegetarian",
    name: "Tikel Gomen",
    nameAm: "ጥቅል ጎመን",
    description: "A mild mix of cabbage, carrots, and potatoes gently spiced with turmeric.",
    price: 320,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "vegetarian-3",
    categoryId: "vegetarian",
    name: "Shiro Alicha",
    nameAm: "ሽሮ አሊቻ",
    description: "A mild, creamy chickpea flour stew finished with garlic and herbs.",
    price: 380,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: ["popular"],
    sortOrder: 3,
  },
  {
    id: "vegetarian-4",
    categoryId: "vegetarian",
    name: "Misir Alicha",
    nameAm: "ምስር አሊቻ",
    description: "Red lentils simmered gently with turmeric and mild spices.",
    price: 360,
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 4,
  },

  // ── Sides ─────────────────────────────────────────────────
  {
    id: "sides-1",
    categoryId: "sides",
    name: "Injera",
    nameAm: "እንጀራ",
    description: "Traditional fermented teff flatbread, soft and tangy.",
    price: 60,
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "sides-2",
    categoryId: "sides",
    name: "Ayib",
    nameAm: "አይብ",
    description: "Freshly made mild cottage cheese, perfect alongside spicy wots.",
    price: 140,
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegetarian", "contains-dairy", "gluten-free"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "sides-3",
    categoryId: "sides",
    name: "Buttered Rice",
    nameAm: "ብተር ሩዝ",
    description: "Fragrant basmati rice cooked with spiced niter kibbeh butter.",
    price: 200,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-dairy", "gluten-free"],
    badges: [],
    sortOrder: 3,
  },
  {
    id: "sides-4",
    categoryId: "sides",
    name: "Kolo",
    nameAm: "ኮሎ",
    description: "Crunchy roasted barley and chickpea snack mix.",
    price: 120,
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 4,
  },

  // ── Desserts ──────────────────────────────────────────────
  {
    id: "desserts-1",
    categoryId: "desserts",
    name: "Honey & Sesame Balls",
    nameAm: "ማር እና ሰሰም ኳሶች",
    description: "Crunchy sesame-coated balls filled with liquid honey.",
    price: 260,
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-nuts"],
    badges: [],
    sortOrder: 1,
  },
  {
    id: "desserts-2",
    categoryId: "desserts",
    name: "Fresh Fruit Platter",
    nameAm: "ትኩስ ፍራፍሬ",
    description: "Seasonal tropical fruits including mango, papaya, banana, and avocado.",
    price: 360,
    image: "https://images.unsplash.com/photo-1493770348161-369560ae357d?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan", "gluten-free"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "desserts-3",
    categoryId: "desserts",
    name: "Baklava",
    nameAm: "ባክላቫ",
    description: "Layers of buttery filo pastry, crushed pistachios, and rose syrup.",
    price: 280,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=900&auto=format&fit=crop",
    isAvailable: false,
    isFeatured: false,
    dietaryTags: ["contains-nuts", "contains-dairy"],
    badges: [],
    sortOrder: 3,
  },

  // ── Drinks ────────────────────────────────────────────────
  {
    id: "drinks-1",
    categoryId: "drinks",
    name: "Ethiopian Coffee (Buna)",
    nameAm: "ቡና",
    description: "Traditional jebena-brewed coffee served with a ceremony.",
    price: 200,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: ["popular"],
    sortOrder: 1,
  },
  {
    id: "drinks-2",
    categoryId: "drinks",
    name: "Macchiato",
    nameAm: "ማኪያቶ",
    description: "Rich espresso topped with a layer of velvety steamed milk.",
    price: 160,
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["contains-dairy"],
    badges: [],
    sortOrder: 2,
  },
  {
    id: "drinks-3",
    categoryId: "drinks",
    name: "Spiced Tea (Shai)",
    nameAm: "ሻይ",
    description: "Black tea infused with cinnamon, clove, and cardamom.",
    price: 120,
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: [],
    badges: [],
    sortOrder: 3,
  },
  {
    id: "drinks-4",
    categoryId: "drinks",
    name: "Hibiscus Juice (Bissena)",
    nameAm: "ብስና",
    description: "Chilled hibiscus infusion, naturally tart and deeply refreshing.",
    price: 160,
    image: "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan"],
    badges: [],
    sortOrder: 4,
  },
  {
    id: "drinks-5",
    categoryId: "drinks",
    name: "Fresh Orange Juice",
    nameAm: "አረንጓዴ ጁስ",
    description: "Freshly squeezed oranges, served ice-cold.",
    price: 150,
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?q=80&w=900&auto=format&fit=crop",
    isAvailable: true,
    isFeatured: false,
    dietaryTags: ["vegan"],
    badges: [],
    sortOrder: 5,
  },
];
